# Base Docker Compose File. We assume usage of redis by most (all) APIs due to usage of OAuth by all services
# We also assume MySQL usage in our code.
version: '2'
services:
    database:
        container_name: fashionplatform_mysql
        image: mysql:5.7
        ports:
            - "3307:3306"
        expose:
            - "3307"
        environment:
            MYSQL_USER: "fashionplatform"
            MYSQL_PASSWORD: "fashionplatform"
            MYSQL_DATABASE: "fashionplatform"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

        networks:
            - main_network

    adminer:
        image: adminer
        container_name: fashionplatform_mysql_client_web
        restart: always
        ports:
            - 10000:8080
        networks:
            - main_network
networks:
    main_network:
        driver: bridge
